sudo: False

language: python

env:
  global:
    # Fixes https://github.com/travis-ci/travis-ci/issues/7940
    - BOTO_CONFIG=/dev/null

matrix:
  include:
    - python: 2.7
    - python: 3.6

install:
  # Install conda
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no
  - conda update conda

  # Install dependencies
  - conda create -n test -c conda-forge python=$TRAVIS_PYTHON_VERSION pip
  - source activate test
  - conda install boto3=1.7.84 botocore=1.10.84 moto=1.3.6 six pytest mock -c conda-forge -y

script:
  - py.test -vv s3fs

notifications:
  email: false
