name: CI

on: [push, pull_request]

jobs:
  test:
    name: Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.6", "3.7", "3.8", "3.9"]

    env:
      BOTO_CONFIG: /dev/null
      AWS_ACCESS_KEY_ID: foobar_key
      AWS_SECRET_ACCESS_KEY: foobar_secret

    steps:
      - name: Checkout source
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Conda Environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          miniconda-version: latest
          activate-environment: test
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        shell: bash -l {0}
        run: |
          conda install -c conda-forge pip botocore aiobotocore "moto>=2.0" pytest flake8 black -y
          pip install git+https://github.com/fsspec/filesystem_spec --no-deps
          conda list
          conda --version

      - name: Install
        shell: bash -l {0}
        run: python setup.py install

      - name: Run Tests
        shell: bash -l {0}
        run: pytest -vv s3fs

      - name: Lint
        shell: bash -l {0}
        run: |
          flake8 s3fs
          black s3fs --check

  test-downstream:
    name: Downstream (py${{ matrix.python-version }}, ${{ matrix.os }} arrow${{ matrix.pyarrow-version }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "windows-latest"]
        python-version: ["3.8"]
        pyarrow-version: [">=1,<2", ">=2,<3"]

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          channels: conda-forge,defaults
          channel-priority: true
          mamba-version: "*"

      - name: Checkout
        uses: actions/checkout@v2
        with:
          # we need the tags present
          fetch-depth: 0

      - name: Ensure tags up to date
        run: >
          git fetch --tags https://github.com/dask/s3fs.git

      - name: Install conda dependencies
        run: >
          mamba install
          -c conda-forge
          'python=${{ matrix.python-version }}'
          'pyarrow${{ matrix.pyarrow-version }}'
          pip
          botocore
          aiobotocore
          moto
          pytest
          dask
          fastparquet
          python-snappy

      - name: Install portions from source
        run: |
          pip install git+https://github.com/intake/filesystem_spec/ --no-deps
          pip install --no-deps .

      - name: conda packages
        run: conda list

      - name: pip freeze
        run: pip freeze

      - name: Run test suite
        run: |
          pytest -vrsx -rA --color=yes downstream_tests
