name: CI

on: [push, pull_request]

jobs:
  test:
    name: Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    env:
      BOTO_CONFIG: /dev/null
      AWS_ACCESS_KEY_ID: foobar_key
      AWS_SECRET_ACCESS_KEY: foobar_secret

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup conda
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: ci/env.yaml
          create-args: >-
            python=${{ matrix.PY }}

      - name: Install
        shell: bash -l {0}
        run: |
          pip install git+https://github.com/fsspec/filesystem_spec
          pip install . --no-deps

      - name: Run Tests
        shell: bash -l {0}
        run: pytest -vv s3fs


  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - uses: pre-commit/action@v3.0.0
