name: CI

on: [push, pull_request]

jobs:
  test:
    name: Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.6", "3.7", "3.8", "3.9"]

    env:
      BOTO_CONFIG: /dev/null
      AWS_ACCESS_KEY_ID: foobar_key
      AWS_SECRET_ACCESS_KEY: foobar_secret

    steps:
      - name: Checkout source
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Conda Environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          channels: conda-forge
          mamba-version: '*'
          activate-environment: s3fs-dev
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        shell: bash -l {0}
        run: |
          mamba env update -f requirements-dev.yml
          pip install git+https://github.com/fsspec/filesystem_spec --no-deps
          conda info
          conda list
          conda --version

      - name: Run Tests
        shell: bash -l {0}
        run: pytest -vv s3fs

      - name: Lint
        shell: bash -l {0}
        run: |
          flake8 s3fs
          black s3fs --check --diff
